//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork112.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class custom
    {
        public int Id { get; set; }
        [DisplayName("姓名")]
        [Required(ErrorMessage = "必填姓名")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "需介於5~50之間")]
        public string cName { get; set; }

        public short cCard { get; set; }
        [DisplayName("帳號")]
        [Required(ErrorMessage = "必填")]
        [StringLength(10, MinimumLength = 3, ErrorMessage = "需介於3~10之間")]
        public string cAccount { get; set; }
        [DisplayName("密碼")]
        [Required(ErrorMessage = "必填")]
        //        [StringLength(10, MinimumLength = 6, ErrorMessage = "需介於6~10之間")]
        [RegularExpression("[a-z]{1}[0-9]{9}", ErrorMessage = "必須是小寫英文")]
        public string cPasswd { get; set; }
    }
}
