//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork112.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class orderlist
    {
        public int Id { get; set; }
        [DisplayName("訂單帳號")]
        public string cAccount { get; set; }
        [DisplayName("產品名稱")]
        public string pTitle { get; set; }
        [DisplayName("訂單數量")]
        public int oAmount { get; set; }
    }
}
