//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork112.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;    

    public partial class product
    {
        public int Id { get; set; }
        [DisplayName("名稱")]
        public string pTitle { get; set; }
        [DisplayName("產地")]
        public string pAddr { get; set; }
        [DisplayName("價格")]
        public int price { get; set; }
        [DisplayName("圖片")]
        public string PImage { get; set; }
        [DisplayName("其他")]
        public string pNote { get; set; }
    }
}
